### ISSUE TITLE
web3.js ^0.18.0 dependency is broken

### ISSUE THREAD

**Issue by adonley** [trufflesuite/truffle-blockchain-utils#3]
See https://github.com/ethereum/web3.js/issues/904 . Dependency needs to be updated to **0.19.1** not **0.19.0** in order to avoid issues.

**Comment by adonley** [comment]
Pull request with updated dep: #4

**Comment by tcoulter** [comment]
Thanks! Going to close this issue for housekeeping. We're tracking it within the Truffle repository.
